# Generated by Django 5.0.7 on 2024-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_deleted_by_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
