# Generated by Django 5.1.3 on 2025-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='repayment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
